### ISSUE TITLE
Stuck at Sign-on Stage

### ISSUE THREAD

**Issue by PratikmohanSrivastav** [mattermost/mattermost-plugin-google-calendar#16]
I uploaded the alpha release of the plugin on my mattermost setup , i was able to complete the setup , however when i am using /calendar connect to connect to my calendar , it gets stuck on the sign-on part after asking for permissions (I am allowing them) , what can I do to resolve this issue i am facing.Thanks!!

**Comment by hanzei** [comment]
Are the any related log messages in your Mattermost server logs?

**Comment by PratikmohanSrivastav** [comment]
![s111](https://user-images.githubusercontent.com/42342924/84817661-f4321e00-b032-11ea-884b-71e335909a45.jpeg)

**Comment by PratikmohanSrivastav** [comment]
hi @hanzei , there were no server logs for this

**Comment by PratikmohanSrivastav** [comment]
just get this image and after some time it shows a message "Invalid state"

**Comment by hanzei** [comment]
Are there errors in your browser console?

**Comment by PratikmohanSrivastav** [comment]
I will try to sign-in once again and see if there are any errors

**Comment by PratikmohanSrivastav** [comment]
this is what i get
![Screenshot from 2020-06-17 00-53-42](https://user-images.githubusercontent.com/42342924/84819045-0b720b00-b035-11ea-8543-62955b8e62c4.png)

**Comment by PratikmohanSrivastav** [comment]
While creating the project that is required for this plugin , I had followed exactly (and only) the steps given in the readme , could it be something related to the OAuth ID , i had kept the application type as web application while creating the OAuth ID

**Comment by PratikmohanSrivastav** [comment]
{"level":"error","ts":1592336233.7855484,"caller":"http/server.go:3059","msg":"http: TLS handshake error from 42.106.42.255:9490: EOF","source":"httpserver"}

{"level":"error","ts":1592336233.7987843,"caller":"http/server.go:3059","msg":"http: TLS handshake error from 42.106.42.255:21354: EOF","source":"httpserver"}

{"level":"error","ts":1592336233.7988508,"caller":"http/server.go:3059","msg":"http: TLS handshake error from 42.106.42.255:33911: EOF","source":"httpserver"}

I got this in my server logs , not sure if it is related to this plugin

**Comment by PratikmohanSrivastav** [comment]
just an update, now i am facing this error
"Error setting up Config Exchange"

**Comment by PratikmohanSrivastav** [comment]
Btw , I haven't enabled the google calendat api , that is not required right?

**Comment by hanzei** [comment]
What is the setup of your Mattermost server? Are you using a proxy? The logs indicate that the google server might not be able to reach your Mattermost server.

**Comment by PratikmohanSrivastav** [comment]
Yes i am using a proxy.Do i need to change something to make this work ?? . I am attaching the server configurations of my server , is there a way i can remove the error by changing any of the configs.

{
    "ServiceSettings": {
        "SiteURL": "https://flipchat.southindia.cloudapp.azure.com",
        "WebsocketURL": "",
        "LicenseFileLocation": "",
        "ListenAddress": ":443",
        "ConnectionSecurity": "TLS",
        "TLSCertFile": "",
        "TLSKeyFile": "",
        "TLSMinVer": "1.2",
        "TLSStrictTransport": false,
        "TLSStrictTransportMaxAge": 63072000,
        "TLSOverwriteCiphers": [],
        "UseLetsEncrypt": true,
        "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
        "Forward80To443": true,
        "TrustedProxyIPHeader": [],
        "ReadTimeout": 300,
        "WriteTimeout": 300,
        "IdleTimeout": 60,
        "MaximumLoginAttempts": 10,
        "GoroutineHealthThreshold": -1,
        "GoogleDeveloperKey": "",
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": true,
        "EnableOutgoingWebhooks": true,
        "EnableCommands": true,
        "EnableOnlyAdminIntegrations": true,
        "EnablePostUsernameOverride": false,
        "EnablePostIconOverride": false,
        "EnableLinkPreviews": true,
        "EnableTesting": false,
        "EnableDeveloper": false,
        "EnableOpenTracing": false,
        "EnableSecurityFixAlert": true,
        "EnableInsecureOutgoingConnections": false,
        "AllowedUntrustedInternalConnections": "",
        "EnableMultifactorAuthentication": false,
        "EnforceMultifactorAuthentication": false,
        "EnableUserAccessTokens": false,
        "AllowCorsFrom": "",
        "CorsExposedHeaders": "",
        "CorsAllowCredentials": false,
        "CorsDebug": false,
        "AllowCookiesForSubdomains": false,
        "ExtendSessionLengthWithActivity": true,
        "SessionLengthWebInDays": 30,
        "SessionLengthMobileInDays": 30,
        "SessionLengthSSOInDays": 30,
        "SessionCacheInMinutes": 10,
"SessionIdleTimeoutInMinutes": 43200,
        "WebsocketSecurePort": 443,
        "WebsocketPort": 80,
        "WebserverMode": "gzip",
        "EnableCustomEmoji": true,
        "EnableEmojiPicker": true,
        "EnableGifPicker": false,
        "GfycatApiKey": "2_KtH_W5",
        "RestrictCustomEmojiCreation": "all",
        "RestrictPostDelete": "all",
        "AllowEditPost": "always",
        "PostEditTimeLimit": -1,
        "TimeBetweenUserTypingUpdatesMilliseconds": 5000,
        "EnablePostSearch": true,
        "MinimumHashtagLength": 3,
        "EnableUserTypingMessages": true,
        "EnableChannelViewedMessages": true,
        "EnableUserStatuses": true,
        "ExperimentalEnableAuthenticationTransfer": true,
        "ClusterLogTimeoutMilliseconds": 2000,
        "CloseUnusedDirectMessages": true,
        "EnablePreviewFeatures": true,
        "EnableTutorial": true,
        "ExperimentalEnableDefaultChannelLeaveJoinMessages": true,
        "ExperimentalGroupUnreadChannels": "disabled",
        "ExperimentalChannelOrganization": false,
        "ExperimentalChannelSidebarOrganization": "disabled",
        "ImageProxyType": "",
        "ImageProxyURL": "",
        "ImageProxyOptions": "",
        "EnableAPITeamDeletion": false,
        "ExperimentalEnableHardenedMode": false,
        "DisableLegacyMFA": true,
        "ExperimentalStrictCSRFEnforcement": false,
        "EnableEmailInvitations": false,
        "DisableBotsWhenOwnerIsDeactivated": true,
        "EnableBotAccountCreation": true,
        "EnableSVGs": false,
        "EnableLatex": false,
        "EnableLocalMode": false,
        "LocalModeSocketLocation": "/var/tmp/mattermost_local.socket"
 
Thanks!!!!

**Comment by PratikmohanSrivastav** [comment]
Yes i am using a proxy.Do i need to change something to make this work ?? . I am attaching the server configurations of my server(have just removed the siteurl) , is there a way i can remove the error by changing any of the configs.

{
"ServiceSettings": {
"SiteURL": "",
"WebsocketURL": "",
"LicenseFileLocation": "",
"ListenAddress": ":443",
"ConnectionSecurity": "TLS",
"TLSCertFile": "",
"TLSKeyFile": "",
"TLSMinVer": "1.2",
"TLSStrictTransport": false,
"TLSStrictTransportMaxAge": 63072000,
"TLSOverwriteCiphers": [],
"UseLetsEncrypt": true,
"LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
"Forward80To443": true,
"TrustedProxyIPHeader": [],
"ReadTimeout": 300,
"WriteTimeout": 300,
"IdleTimeout": 60,
"MaximumLoginAttempts": 10,
"GoroutineHealthThreshold": -1,
"GoogleDeveloperKey": "",
"EnableOAuthServiceProvider": false,
"EnableIncomingWebhooks": true,
"EnableOutgoingWebhooks": true,
"EnableCommands": true,
"EnableOnlyAdminIntegrations": true,
"EnablePostUsernameOverride": false,
"EnablePostIconOverride": false,
"EnableLinkPreviews": true,
"EnableTesting": false,
"EnableDeveloper": false,
"EnableOpenTracing": false,
"EnableSecurityFixAlert": true,
"EnableInsecureOutgoingConnections": false,
"AllowedUntrustedInternalConnections": "",
"EnableMultifactorAuthentication": false,
"EnforceMultifactorAuthentication": false,
"EnableUserAccessTokens": false,
"AllowCorsFrom": "",
"CorsExposedHeaders": "",
"CorsAllowCredentials": false,
"CorsDebug": false,
"AllowCookiesForSubdomains": false,
"ExtendSessionLengthWithActivity": true,
"SessionLengthWebInDays": 30,
"SessionLengthMobileInDays": 30,
"SessionLengthSSOInDays": 30,
"SessionCacheInMinutes": 10,
"SessionIdleTimeoutInMinutes": 43200,
"WebsocketSecurePort": 443,
"WebsocketPort": 80,
"WebserverMode": "gzip",
"EnableCustomEmoji": true,
"EnableEmojiPicker": true,
"EnableGifPicker": false,
"GfycatApiKey": "2_KtH_W5",
"RestrictCustomEmojiCreation": "all",
"RestrictPostDelete": "all",
"AllowEditPost": "always",
"PostEditTimeLimit": -1,
"TimeBetweenUserTypingUpdatesMilliseconds": 5000,
"EnablePostSearch": true,
"MinimumHashtagLength": 3,
"EnableUserTypingMessages": true,
"EnableChannelViewedMessages": true,
"EnableUserStatuses": true,
"ExperimentalEnableAuthenticationTransfer": true,
"ClusterLogTimeoutMilliseconds": 2000,
"CloseUnusedDirectMessages": true,
"EnablePreviewFeatures": true,
"EnableTutorial": true,
"ExperimentalEnableDefaultChannelLeaveJoinMessages": true,
"ExperimentalGroupUnreadChannels": "disabled",
"ExperimentalChannelOrganization": false,
"ExperimentalChannelSidebarOrganization": "disabled",
"ImageProxyType": "",
"ImageProxyURL": "",
"ImageProxyOptions": "",
"EnableAPITeamDeletion": false,
"ExperimentalEnableHardenedMode": false,
"DisableLegacyMFA": true,
"ExperimentalStrictCSRFEnforcement": false,
"EnableEmailInvitations": false,
"DisableBotsWhenOwnerIsDeactivated": true,
"EnableBotAccountCreation": true,
"EnableSVGs": false,
"EnableLatex": false,
"EnableLocalMode": false,
"LocalModeSocketLocation": "/var/tmp/mattermost_local.socket"

Thanks!!!!

**Comment by promehul** [comment]
@hanzei any help? I am also stuck exactly the same way

**Comment by hanzei** [comment]
Could you try sshing on your MM server and checking if you can hit `https://googleapis.com/`?

**Comment by nmueller-eyeo** [comment]
@hanzei We are experiencing the same issue. I've tried it on multiple servers, some with a reverse proxy and others without a proxy. All of them can reach googleapis.com, but all of them are stuck at the sign-in stage for the Google permissions prompt.

**Comment by hanzei** [comment]
@hahmadia Did ever you encounter this error while developing? Do you have ideas how to further debug it?

**Comment by hahmadia** [comment]
Make sure the Google calendar API is enabled in your Google accounts. Otherwise ... I wouldn't have any idea.

**Comment by svenseeberg** [comment]
Has anyone found the/a solution? I'm currently trying to navigate around this issue as well.

**Comment by svenseeberg** [comment]
> Make sure the Google calendar API is enabled in your Google accounts. Otherwise ... I wouldn't have any idea.

Yes, that was the issue in my case. I thought I had done this in the past, but I did not. 

After creating the project, go to https://console.cloud.google.com/apis  and select "Libraries" in the left menu. Then select "Google Calendar API" and activate it. You also need to go to domains and add your Mattermost domain there.

I'll open a PR with an extended description in the README.md.
