### ISSUE TITLE
Use of Deprecated function `New` in getting calendar service

### ISSUE THREAD

**Issue by abdulsmapara** [mattermost/mattermost-plugin-google-calendar#19]
Presently, [1] uses `func New(client *http.Client) (*Service, error)` to obtain a new calendar service. The function is deprecated as documented in [2]. 
Instead, the function `func NewService(ctx context.Context, opts ...option.ClientOption) (*Service, error)` should be used.

[1] https://github.com/mattermost/mattermost-plugin-google-calendar/blob/master/server/utils.go#L76
[2] https://godoc.org/google.golang.org/api/calendar/v3#New

![Deprecated-Function-New-Should-Use-New-Service](https://user-images.githubusercontent.com/32198670/87912683-6e6b1d80-ca8b-11ea-8907-92994ef0096a.png)

**Comment by hanzei** [comment]
Good catch @abdulsmapara :+1: Are you interested in fixing this?

**Comment by abdulsmapara** [comment]
Yes, would like to fix this!
