### ISSUE TITLE
Create functions for ExecuteCommand Switch statement

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-google-calendar#2]
### Summary
The `ExecuteCommand()` function handles the slash commands for a plugin, with the use of a `switch statement`.  Currently each `case` contains all the logic to handle each slash command.  This ticket is a request to modify each `case` to return a call to a function which will contain all of the logic.  This will make the `ExecuteCommand()` function more readable and easy to understand, plus delegate a function to handle each slash command input.

Here is the relevant code that needs to be modified:
https://github.com/mattermost/mattermost-plugin-google-calendar/blob/master/server/command_hooks.go#L83

The https://github.com/mattermost/mattermost-plugin-demo example has an example for the proposed changes.
https://github.com/mattermost/mattermost-plugin-demo/blob/master/server/command_hooks.go#L111

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by abdulsmapara** [comment]
I am interested in solving this issue.

**Comment by hanzei** [comment]
Awesome, thanks @abdulsmapara :rocket:

**Comment by abdulsmapara** [comment]
I have completed this task, but I have observed two issues that lead to unsuccessful `make` -
1. config declaration at line 373 shadows declaration at line 339 : server/utils.go
2. golint fails on running `make`
Still should I go ahead with submitting PR for this issue ?

**Comment by jfrerich** [comment]
Hi @abdulsmapara.  You can submit the PR with the linting error.  

The shadow declaration warning occurs when one is redeclaring a variable that has already been declared.  It will look something like this...  Note the second line (line 373) is use the `:=` which is redeclaring the config variable.  You can remove the `:` from the second line and should remove the error.
```go
339: config := getConfig()
373: config := getConfig()
```

**Comment by abdulsmapara** [comment]
Yeah, for the purpose of making sure it builds, I have commented golint in make file and already removed : in the 373rd line.
Thanks for the reply, I can now go ahead with the PR for this issue !

**Comment by jfrerich** [comment]
I look forward to the PR and seeing the refactor!
