### ISSUE TITLE
Add autocomplete icon

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-google-calendar#22]
Since v5.24 slash commands can provide an `svg` via  `AutocompleteIconData` in `model.Command` that is then shown in the autocomplete list. This ticket is about adding the icon in `assets` to the slash command.

Include screenhots from a dark and a bright theme in the PR description, as there might be the need for a separate icon with a white background for autocomplete.

Similar PRs:
For GitHub plugin https://github.com/mattermost/mattermost-plugin-github/pull/359
For Jira plugin https://github.com/mattermost/mattermost-plugin-jira/pull/653

**Comment by goldsziggy** [comment]
Hi I was wondering if I could give this issue a go?

**Comment by hanzei** [comment]
Sorry @goldsziggy, someone else already opened https://github.com/mattermost/mattermost-plugin-google-calendar/pull/23. https://github.com/mattermost/mattermost-plugin-autolink/issues/118 might be an interesting alternative for you.

**Comment by ByeongsuPark** [comment]
Hi @hanzei. I have a question related to the PR you mentioned. I looked into it. But I can't see the code for autocomplete icon. Is this issue still valid?

**Comment by hanzei** [comment]
You are correct. https://github.com/mattermost/mattermost-plugin-google-calendar/pull/23 only added the autocomplete data. The icon is still missing. Do you want to work on this @ByeongsuPark?

**Comment by ByeongsuPark** [comment]
Yes. I woud like to take this issue.
