### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by lizat** [mattermost/mattermost-plugin-google-calendar#26]
I want to install your plugin, but it isn't on Marketplace, so reading the instructions point '7. Upload the plugin to Mattermost...' I can't figure out how, I have no upload button. I am currently on a trial account does this make a difference?

Thank you

**Comment by hanzei** [comment]
Are you using Mattermost Cloud by any chance?

**Comment by lizat** [comment]
At the moment yes we are just playing with the 14 day free trial

**Comment by hanzei** [comment]
Unfortunately, plugins can only be installed via the Marketplace on Mattermost Cloud. Given that this plugin isn't in the Marketplace, it can't be installed there.
