### ISSUE TITLE
I assume this is dead?

### ISSUE THREAD

**Issue by NeckBeardPrince** [mattermost/mattermost-plugin-google-calendar#34]

**Comment by levb** [comment]
We are focusing on https://github.com/mattermost/mattermost-app-gcal as part of our upcoming Mattermost Apps release in 2022. 1/5 we should keep the repo until Apps 1.0 and the gCal app are released.

cc @mickmister @hanzei

**Comment by levb** [comment]
@NeckBeardPrince the goal is for new app to be deployable as a plugin, but will also require that `mattermost-plugin-apps` is installed.
