### ISSUE TITLE
`/gcal viewcal` mentions "showing events for the upcoming week" but shows 2 weeks of events

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/mattermost-plugin-google-calendar#48]
When running `/gcal viewcal` it returns events for Tuesday Oct 10th (the past) until Tuesday October 24th (2 weeks into the future - 1 day).
![Screenshot 2023-10-11 at 9 52 23 AM](https://github.com/mattermost/mattermost-plugin-google-calendar/assets/46071821/79dc3d73-1aeb-4c4a-a7c2-528be78962fd)

**Comment by fmartingr** [comment]
Closing this in favour of https://github.com/mattermost/mattermost-plugin-mscalendar/issues/325
