### ISSUE TITLE
Location field missbehavior

### ISSUE THREAD

**Issue by fmartingr** [mattermost/mattermost-plugin-google-calendar#78]
Investigate the report of this behaviour using the create event modal:

> Information entered in the "Location" field in the Create Calendar Event window in MM is not transferring to the location value in Google Calendar and not showing in the 5-minute reminder. 

> But entering Location info in the "Description" field will transfer to the Location field in Google Calendar and show up in the 5-minute reminder.

**Comment by Kshitij-Katiyar** [comment]
@fmartingr Can you please elaborate on the issue and maybe share some video about this? Below I have created the event through the Google Calendar plugin and included the location in the location field only. The same was reflected on the Google side as well I got the reminder as well. Below are some screenshots:

![Screenshot from 2024-05-31 18-57-01](https://github.com/mattermost/mattermost-plugin-google-calendar/assets/90389917/5e2a531f-15e6-4915-a780-54260c972391)
![WhatsApp Image 2024-05-31 at 18 57 27](https://github.com/mattermost/mattermost-plugin-google-calendar/assets/90389917/7ff0b4a7-4da3-4226-9276-2cc6a97dc52a)

Can you please share the steps to reproduce this maybe or any other additional information is appreciated.

**Comment by mickmister** [comment]
> But entering Location info in the "Description" field will transfer to the Location field in Google Calendar and show up in the 5-minute reminder.

@Kshitij-Katiyar I think the 5-minute reminder is referring to the Mattermost plugin's DM reminder

**Comment by Kshitij-Katiyar** [comment]
> > But entering Location info in the "Description" field will transfer to the Location field in Google Calendar and show up in the 5-minute reminder.
> 
> @Kshitij-Katiyar I think the 5-minute reminder is referring to the Mattermost plugin's DM reminder

sure @mickmister I didn't know about that. Let me check that but still, the location field is correctly getting configured on the google side.

**Comment by fmartingr** [comment]
I will gather more information and get back to you @Kshitij-Katiyar.

**Comment by Kshitij-Katiyar** [comment]
> I will gather more information and get back to you @Kshitij-Katiyar.

@fmartingr Is there any update on this ?

**Comment by fmartingr** [comment]
> > I will gather more information and get back to you @Kshitij-Katiyar.
> 
> @fmartingr Is there any update on this?

We have requested a video from the customer to understand what is the problem they are experiencing. Still waiting on it.

**Comment by wiggin77** [comment]
> We have requested a video from the customer to understand what is the problem they are experiencing.

Does this mean we are unable to reproduce this?

**Comment by fmartingr** [comment]
> > We have requested a video from the customer to understand what is the problem they are experiencing.
> 
> Does this mean we are unable to reproduce this? @fmartingr

What we think is that is not that there's a problem with the field itself since it's saving correctly, but there's a problem displaying the field in some part of the UI.

**Comment by darias416** [comment]
@fmartingr the customer confirmed this issue has been resolved for them as of version 1.1.1

cc: @wiggin77
