### ISSUE TITLE
Gcal plugin - Mobile shows a duplicate Summary option in the slash command auto-complete

### ISSUE THREAD

**Issue by wiggin77** [mattermost/mattermost-plugin-google-calendar#91]
Mobile shows a duplicate Summary option in the slash command auto-complete.

![gcal-bug](https://github.com/user-attachments/assets/eaf4c4f0-24f1-4845-b47e-17f392ccdbe7)
 

If it matters, they both work.

See https://mattermost.atlassian.net/browse/MM-54115

**Comment by fmartingr** [comment]
`/gcal summary` autocomplete was removed in favor of `/gcal today` and `/gcal tomorrow`.

https://github.com/mattermost/mattermost-plugin-mscalendar/commit/7f1bbcd544c37b71db94265931517247b5479374
